# Line Graph

```{r}
x <- c(1,2,3,4,5)
y <- c(3,7,8,9,12)
```

```{r}
plot(x,y,type="l")
```

```{r}
plot(x,y,main="My Graph",xlab="The x-axis",ylab="The y-axis")
```

```{r}
plot(x,y,type="l",col="red")
```

```{r}
plot(x,y,type = "l",col="red",lwd=5,lty=3)
```

```{r}
plot(x,y,type="l",col="blue")
#lines(x,y,type="l",col="red")
```

# Scatter Plot

```{r}
x <- c(5,7,8,7,2,2,9,4,11,12,9,6)
y <- c(99,86,87,88,111,103,87,94,78,77,85,86)
plot(x,y,main= "Observation of cars",xlab="car age",ylab = "car Sped") 
```

```{r}
# day one, the age and speed of 12 cars:
x1 <- c(5,7,8,7,2,2,9,4,11,12,9,6)
y1 <- c(99,86,87,88,111,103,87,94,78,77,85,86)

# day two, the age and speed of 15 cars:
x2 <-c(2,2,8,1,15,8,12,9,7,3,11,4,7,14,12)
y2 <-c(100,105,84,105,90,99,90,95,94,100,79,112,91,80,85)

plot(x1,y1,main="Observation of cars",xlab="car age",ylab="Car speed",cex=2)
point(x2,y2,col="blue",cex=2)
```

# Pie Chart

```{r}
x <- c(10,20,40)
pie(x,init.angle = 90)
```

```{r}
# Create a vector of labels
mylabel <- c("Apples","Bananas","Cherries","Dates")
# Display the pie chart with labels
pie(x, label = mylabel, main ="Fruits")


```

```{r}
# Create a vector of colors
colors <- c("blue","yellow","green","black")
# Display the pie chart with colors
pie(x, label = mylabel, main ="Fruits", col = colors)
# Display the explanation box
legend("bottomright", mylabel, fill = colors)

```

# Bar Charts

```{r}
x <- c("A","B","C","D")
y <- c(2,4,6,8)
barplot(y,names.arg = x,col = "red",horiz = TRUE)
```

```{r}
barplot(y,names.arg = x,density = 10)
```

```{r}
barplot(y,names.arg = x,width = c(1,2,3,4))
```
